-- 코드를 입력하세요
SELECT B.AUTHOR_ID,B.AUTHOR_NAME,B.CATEGORY,SUM(BS.SALES *  B.PRICE) AS TOTAL_SALES
FROM BOOK_SALES AS BS
JOIN (SELECT B.*,A.AUTHOR_NAME
        FROM BOOK AS B
        INNER JOIN AUTHOR AS A
        ON A.AUTHOR_ID  = B.AUTHOR_ID
        ) AS B
ON B.BOOK_ID = BS.BOOK_ID
WHERE BS.SALES_DATE >= '2022-01-01' AND BS.SALES_DATE < '2022-02-01'
GROUP BY AUTHOR_ID,CATEGORY
ORDER BY AUTHOR_ID ASC, CATEGORY DESC
;