-- 코드를 입력하세요
WITH TT AS (SELECT AI.ANIMAL_ID
FROM ANIMAL_INS AS AI
INNER JOIN ANIMAL_OUTS AS AO
ON AI.ANIMAL_ID = AO.ANIMAL_ID
ORDER BY TIMESTAMPDIFF(day,AI.DATETIME,AO.DATETIME) DESC LIMIT 2)

SELECT AI.ANIMAL_ID, AI.NAME
FROM TT AS T
INNER JOIN ANIMAL_INS AS AI
ON AI.ANIMAL_ID = T.ANIMAL_ID