-- 코드를 입력하세요
SELECT D.CAR_ID, D.CAR_TYPE, CAST(D.DAILY_FEE * (1 -(C.DISCOUNT_RATE * 0.01)) * 30 AS SIGNED) AS FEE
FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS C
INNER JOIN (SELECT DISTINCT B.CAR_ID, B.DAILY_FEE, B.CAR_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS A   
RIGHT OUTER JOIN CAR_RENTAL_COMPANY_CAR  AS B
ON A.CAR_ID = B.CAR_ID
WHERE (B.CAR_TYPE = 'SUV' OR B.CAR_TYPE = '세단')
AND (A.START_DATE IS NULL) OR B.CAR_ID NOT IN (select CAR_ID
    from CAR_RENTAL_COMPANY_RENTAL_HISTORY
    where END_DATE>='2022-11-01'
    and START_DATE<'2022-12-01') ) AS D
ON C.CAR_TYPE  = D.CAR_TYPE
WHERE C.DURATION_TYPE like ("%30%")
AND D.DAILY_FEE * (1 -(C.DISCOUNT_RATE * 0.01)) *30 >= 500000
AND D.DAILY_FEE * (1 -(C.DISCOUNT_RATE * 0.01)) *30 < 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;

# SELECT a.car_id,a.CAR_TYPE,ROUND(a.DAILY_FEE * 30 * (100 - b.DISCOUNT_RATE) / 100, 0) AS FEE
# FROM CAR_RENTAL_COMPANY_CAR as a join 
# (select * from CAR_RENTAL_COMPANY_DISCOUNT_PLAN where DURATION_TYPE ='30일 이상') b 
# on a.CAR_TYPE=b.CAR_TYPE
# where a.CAR_TYPE in ('세단','suv')
# and a.car_id not in (
#     select car_id
#     from CAR_RENTAL_COMPANY_RENTAL_HISTORY
#     where END_DATE>='2022-11-01'
#     and START_DATE<'2022-12-01'
# )
# group by a.car_id
# having FEE BETWEEN 500000 AND 1999999
# order by FEE DESC,CAR_TYPE ASC,CAR_ID DESC


# SELECT DISTINCT B.CAR_ID, B.DAILY_FEE, B.CAR_TYPE
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS A   
# RIGHT OUTER JOIN CAR_RENTAL_COMPANY_CAR  AS B
# ON A.CAR_ID = B.CAR_ID
# WHERE (B.CAR_TYPE = 'SUV' OR B.CAR_TYPE = '세단')
# AND (A.START_DATE IS NULL 
#      OR (A.START_DATE >= '2022-12-01' 
#          OR A.END_DATE < '2022-11-01'))
         

    
