-- 코드를 입력하세요
SELECT ai.NAME,ai.DATETIME FROM ANIMAL_INS as ai
WHERE ai.ANIMAL_ID not in (SELECT ai.ANIMAL_ID
FROM ANIMAL_INS as ai
JOIN ANIMAL_OUTS as ao
ON ai.ANIMAL_ID = ao.ANIMAL_ID
)
ORDER BY DATETIME ASC limit 3;

