-- 코드를 입력하세요
SELECT HISTORY_ID,TRUNCATE((1- (IFNULL(DISCOUNT_RATE,0) *0.01)) * DAILY_FEE * TIME,0) AS FEE
FROM    (SELECT CH.*,CR.DAILY_FEE,CR.CAR_TYPE, TIMESTAMPDIFF(day,CH.START_DATE,CH.END_DATE) +1 AS TIME,
            CASE 
                WHEN 90 <= TIMESTAMPDIFF(day,CH.START_DATE,CH.END_DATE) THEN '90'
                WHEN 30 <= TIMESTAMPDIFF(day,CH.START_DATE,CH.END_DATE) THEN '30'
                WHEN 7  <= TIMESTAMPDIFF(day,CH.START_DATE,CH.END_DATE) THEN '7'
                ELSE '0' END AS DUR
            FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS CH
                INNER JOIN CAR_RENTAL_COMPANY_CAR AS CR
                ON CH.CAR_ID = CR.CAR_ID
            WHERE CR.CAR_TYPE ='트럭' ) AS T2
    LEFT OUTER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS CP
    ON REGEXP_REPLACE(CP.DURATION_TYPE,'[^0-9]+','') = T2.DUR AND CP.CAR_TYPE = T2.CAR_TYPE
ORDER BY FEE DESC, HISTORY_ID DESC