-- 코드를 입력하세요
SELECT B.APNT_NO, A.PT_NAME, B.PT_NO, B.MCDP_CD, C.DR_NAME, B.APNT_YMD
FROM PATIENT AS A
INNER JOIN APPOINTMENT AS B ON A.PT_NO = B.PT_NO
INNER JOIN DOCTOR AS C ON C.MCDP_CD = B.MCDP_CD AND B.MDDR_ID = C.DR_ID
WHERE DATE_FORMAT(B.APNT_YMD,'%Y-%m-%d') ='2022-04-13' AND APNT_CNCL_YN = 'N'
ORDER BY B.APNT_YMD ASC