-- 코드를 입력하세요
SELECT ugu.USER_ID, ugu.NICKNAME, ugp.TOTAL_SALES 
FROM USED_GOODS_USER as ugu
JOIN (SELECT WRITER_ID,sum(PRICE) as TOTAL_SALES
FROM USED_GOODS_BOARD as ugb
WHERE ugb.STATUS = "DONE"
GROUP BY WRITER_ID
HAVING TOTAL_SALES >= 700000) as ugp 
ON ugp.WRITER_ID = ugu.USER_ID 
ORDER BY TOTAL_SALES ASC;


# SELECT * FROM USED_GOODS_BOARD;

# SELECT WRITER_ID,sum(PRICE) as TOTAL_SALES
# FROM USED_GOODS_BOARD as ugb
# WHERE ugb.STATUS = "DONE"
# GROUP BY WRITER_ID;