WITH REVIEW_COUNT AS (
    SELECT MEMBER_ID, COUNT(*) AS REVIEW_COUNT
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY REVIEW_COUNT DESC LIMIT 1
),
MAX_REVIEW_MEMBER AS (
    SELECT DISTINCT MEMBER_ID
    FROM REST_REVIEW 
    WHERE MEMBER_ID = (SELECT MEMBER_ID FROM REVIEW_COUNT)
)
SELECT MP.MEMBER_NAME,RR.REVIEW_TEXT, DATE_FORMAT(RR.REVIEW_DATE ,"%Y-%m-%d")  AS REVIEW_DATE
FROM MEMBER_PROFILE AS MP
JOIN REST_REVIEW AS RR
ON MP.MEMBER_ID = RR.MEMBER_ID
WHERE MP.MEMBER_ID IN (SELECT MEMBER_ID FROM MAX_REVIEW_MEMBER)
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC
;
            