-- 코드를 입력하세요

SELECT CONCAT("/home/grep/src/",ugb.BOARD_ID,"/", ugf.FILE_ID,ugf.FILE_NAME,ugf.FILE_EXT) as FILE_PATH 
FROM USED_GOODS_FILE as ugf 
JOIN (SELECT BOARD_ID,VIEWS FROM USED_GOODS_BOARD  
WHERE VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD )) as ugb
ON ugf.BOARD_ID = ugb.BOARD_ID
ORDER BY ugf.FILE_ID DESC;


